# Generated by Django 4.1.3 on 2023-02-20 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quizuser_question_max_score_alter_answer_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempts',
            name='quizUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.quizuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attempts',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.answer'),
        ),
    ]
