# Generated by Django 4.1.3 on 2023-02-20 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Tip title')),
            ],
        ),
        migrations.CreateModel(
            name='TipDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Tip description')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tip', to='pages.tip')),
            ],
        ),
    ]
