# Generated by Django 4.1.3 on 2023-02-20 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_user_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='Total Score')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=6, verbose_name='Maximum score'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.question'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
